# Generated by Django 4.0 on 2021-12-31 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_teachers_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='code',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='code',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='code',
        ),
    ]
