# Generated by Django 4.0 on 2021-12-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_remove_students_code_remove_subjects_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='subjects',
            name='students',
            field=models.ManyToManyField(to='schoolapp.Students'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='teachers',
            field=models.ManyToManyField(to='schoolapp.Teachers'),
        ),
    ]
